// <auto-generated />
namespace Roflan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _123111111111113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123111111111113));
        
        string IMigrationMetadata.Id
        {
            get { return "201805191649474_123111111111113"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
